-- AlterTable
ALTER TABLE "PostVersion" ADD COLUMN     "changedFields" TEXT NOT NULL DEFAULT '[]',
ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "content" DROP NOT NULL,
ALTER COLUMN "tags" DROP NOT NULL,
ALTER COLUMN "tags" DROP DEFAULT;
